name: overlay_support_example
description: example for overlay_support library

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.13.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  overlay_support:
    path: ../
  cupertino_icons:
  material_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
