name: overlay_support
description: provider support for overlay, easy to build toast and internal notification
version: 2.1.2
homepage: https://github.com/boyan01/overlay_support

environment:
  sdk: ">=3.13.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  async:
  cupertino_ui:
  material_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:

flutter:
